import React from "react";
import Footer from "../Footer/Footer";
import NavBar from "../NavBar/NavBar";
import "./privacy.css";
function privacy() {
  return (
    <>
      <NavBar />
      <div className="terms">
        <h6 class="date">Published: June 10, 2018</h6>
        <h6 class="date-updated">Updated: June 25, 2018</h6>
        <h1 class="title">Privacy Policy</h1>
        <h3 class="list-txt">General Terms</h3>
        <p class="text">
          By accessing and placing an order with, you confirm that you are in
          agreement with and bound by the terms of service contained in the
          Terms & Conditions outlined below. These terms apply to the entire
          website and any email or other type of communication between you and.
        </p>
        <p class="text">
          Under no circumstances shall team be liable for any direct, indirect,
          special, incidental or consequential damages, including, but not
          limited to, loss of data or profit, arising out of the use, or the
          inability to use, the materials on this site, even if team or an
          authorized representative has been advised of the possibility of such
          damages. If your use of materials from this site results in the need
          for servicing, repair or correction of equipment or data, you assume
          any costs thereof.
        </p>

        <p class="text">
          will not be responsible for any outcome that may occur during the
          course of usage of our resources. We reserve the rights to change
          prices and revise the resources usage policy in any moment.
        </p>
        <h3 class="list-txt">License</h3>
        <p class="text">
          Skywart-edu grants you a revocable, non-exclusive, non-transferable,
          limited license to download, install and use our service strictly in
          accordance with the terms of this Agreement.
        </p>
        <p class="text">
          These Terms & Conditions are a contract between you and Skywart-edu
          (referred to in these Terms & Conditions as "Skywart- edu ", "us",
          "we" or "our"), the provider of the Skywart-edu website and the
          services accessible from the Skywart-edu website (which are
          collectively referred to in these Terms & Conditions as the
          "Skywart-edu Service").
        </p>
        <p class="text">
          You are agreeing to be bound by these Terms & Conditions. If you do
          not agree to these Terms & Conditions, please do not use the Service.
          In these Terms & Conditions, "you" refers both to you as an individual
          and to the entity you represent. If you violate any of these Terms &
          Conditions, we reserve the right to cancel your account or block
          access to your account without notice
        </p>
        <h3 class="list-txt">Definitions and key terms</h3>
        <p>For this Terms & Conditions:</p>

        <p class="text">
          Cookie: small amount of data generated by a website and saved by your
          web browser. It is used to identify your browser, provide analytics,
          remember information about you such as your language preference or
          login information.
        </p>

        <p class="text">
          Company: when this policy mentions "Company" "we," "us, or "our" it
          refers to SKYWART PRIVATE LIMITED, PLOT NO 4.KHASRA NO:317 S TIWARIPUR
          PARGANA BKTLUCKNOW (UP) that is responsible for your information under
          this Privacy Policy
        </p>

        <p class="text">
          {" "}
          Country: where Skywart-edu or the owners/founders of Skywart-edu are
          based in this case is INDIA.
        </p>

        <p class="text">
          {" "}
          Customer: refers to the company any organization or person that signs
          up to use the Skywart-edu Service to manage the relationships with
          your consumers or service users,
        </p>

        <p class="text">
          Device: any internet connected device such as a phone, tablet computer
          or any other device that can be used to visit Skywart-edu and use the
          services.
        </p>

        <p class="text">
          IP address: Every device connected to the Internet is assigned a
          number known as an Internet protocol (IP) address. These numbers are
          usually assigned in geographic blocks. An IP address can often be used
          to identify the location from which a device is connecting to the
          Internet.
        </p>

        <p class="text">
          Personnel: refers to those individuals who are employed by Skywart-edu
          or are under contract to perform a service on behalf of one of the
          parties
        </p>

        <p class="text">
          Personal Data: any information that directly, indirectly, or in
          connection with other information - Including a personal
          identification number - allows for the identification or
          identifiability of a natural person
        </p>

        <p class="text">
          {" "}
          Service: refers to the service provided by Skywart-edu as described in
          the relative terms (if available) and on this platfor
        </p>

        <p class="text">
          {" "}
          Third-party service: refers to advertisers, contest sponsors,
          promotional and marketing partners, and others who provide our content
          or whose products or services we think may interest you.{" "}
        </p>
      </div>
      <Footer />
    </>
  );
}

export default privacy;
